import streamlit as st

st.set_page_config(
    page_title="About | Urban Heat Island Analyzer",
    page_icon="🌡️",
    layout="wide"
)

# Sidebar
with st.sidebar:
    st.title("Urban Heat Island Analyzer")
    st.write("Analyze and visualize urban heat islands in cities worldwide.")
    
    # Navigation
    st.subheader("Navigation")
    st.page_link("app.py", label="Home", icon="🏠")
    st.page_link("pages/community_input.py", label="Community Input", icon="📝")
    st.page_link("pages/analysis.py", label="Heat Island Analysis", icon="📊")
    st.page_link("pages/about.py", label="About", icon="ℹ️")

# Main content
st.title("About Urban Heat Islands")

st.markdown("""
## What is an Urban Heat Island?

An urban heat island (UHI) is an urban or metropolitan area that is significantly warmer than its surrounding rural areas due to human activities. The temperature difference is usually more noticeable at night than during the day and most apparent when winds are weak.

### Causes of Urban Heat Islands:

1. **Reduced Natural Landscape**: Replacing natural land cover with pavement, buildings, and other infrastructure reduces the natural cooling effects of shade and evaporation of water from soil and plants.

2. **Urban Materials**: Dark surfaces like asphalt roads and dark roofs absorb more solar radiation than natural landscapes, heating urban areas.

3. **Urban Geometry**: The height and spacing of buildings affect wind flow and the ability to release heat.

4. **Heat Generated by Human Activities**: Vehicles, air conditioning, and industrial processes release heat into the urban environment.

5. **Reduced Airflow**: Buildings can reduce natural air flow and trap heat.

### Impacts of Urban Heat Islands:

- **Increased Energy Consumption**: Higher demand for air conditioning
- **Elevated Emissions**: Increased energy consumption leads to higher levels of air pollutants and greenhouse gases
- **Heat-Related Illness and Mortality**: Higher temperatures can lead to respiratory difficulties, heat cramps, heat exhaustion, and heat stroke
- **Water Quality Issues**: Hot pavement and rooftops can heat stormwater runoff, which affects water quality
- **Biodiversity Effects**: Changes in urban plant and animal populations

## Our Platform's Mission

The Urban Heat Island Analyzer aims to:

1. **Map and Visualize** temperature patterns in urban areas
2. **Identify Hot Spots** where heat island effects are most severe
3. **Engage Communities** in data collection and awareness
4. **Suggest Interventions** to mitigate heat island effects
5. **Track Changes** over time to measure the effectiveness of interventions

## How You Can Help

- **Contribute Data**: Submit temperature readings from your location
- **Spread Awareness**: Share information about urban heat islands with your community
- **Implement Solutions**: Plant trees, install green roofs, use cool pavement technologies
- **Support Policies**: Advocate for urban planning policies that address heat islands

## Eco-Friendly Interventions for Urban Heat Islands

### Green Infrastructure
- Increase urban tree canopy
- Create green roofs and walls
- Develop pocket parks and community gardens
- Preserve and restore urban wetlands

### Cool Materials
- Install reflective/cool roofs
- Use light-colored, permeable pavement
- Implement cool walls with reflective coatings

### Urban Design
- Design streets for shade and airflow
- Incorporate water features for cooling
- Create compact development with strategic open spaces
- Design buildings with natural ventilation features

### Policy Measures
- Implement heat island reduction in building codes
- Create incentives for green infrastructure
- Develop comprehensive heat island mitigation plans
- Protect and expand urban parks and green spaces
""")

# Image placeholder for urban heat island diagram
st.markdown("""
<div style="text-align: center;">
    <svg width="700" height="300" xmlns="http://www.w3.org/2000/svg">
        <!-- Background -->
        <rect width="700" height="300" fill="#f8f9fa" />
        
        <!-- Sky background gradient -->
        <defs>
            <linearGradient id="skyGradient" x1="0%" y1="0%" x2="0%" y2="100%">
                <stop offset="0%" style="stop-color:#87CEEB;stop-opacity:1" />
                <stop offset="100%" style="stop-color:#E0F7FA;stop-opacity:1" />
            </linearGradient>
        </defs>
        <rect width="700" height="200" fill="url(#skyGradient)" />
        
        <!-- Ground -->
        <rect x="0" y="200" width="700" height="100" fill="#8BC34A" />
        
        <!-- Rural area on left -->
        <g>
            <!-- Trees -->
            <path d="M50,200 L70,160 L90,200 Z" fill="#2E7D32" />
            <rect x="65" y="200" width="10" height="20" fill="#795548" />
            
            <path d="M100,200 L120,150 L140,200 Z" fill="#2E7D32" />
            <rect x="115" y="200" width="10" height="20" fill="#795548" />
            
            <path d="M20,200 L40,170 L60,200 Z" fill="#2E7D32" />
            <rect x="35" y="200" width="10" height="20" fill="#795548" />
            
            <!-- Small house -->
            <rect x="75" y="180" width="30" height="20" fill="#FFECB3" />
            <polygon points="75,180 105,180 90,165" fill="#D84315" />
        </g>
        
        <!-- City in center -->
        <g>
            <!-- Buildings -->
            <rect x="200" y="120" width="40" height="80" fill="#B0BEC5" />
            <rect x="250" y="100" width="30" height="100" fill="#90A4AE" />
            <rect x="290" y="80" width="50" height="120" fill="#78909C" />
            <rect x="350" y="60" width="40" height="140" fill="#607D8B" />
            <rect x="400" y="90" width="60" height="110" fill="#546E7A" />
            <rect x="470" y="110" width="30" height="90" fill="#455A64" />
            
            <!-- Windows -->
            <g fill="#FFEB3B">
                <rect x="210" y="130" width="8" height="8" />
                <rect x="225" y="130" width="8" height="8" />
                <rect x="210" y="145" width="8" height="8" />
                <rect x="225" y="145" width="8" height="8" />
                <rect x="210" y="160" width="8" height="8" />
                <rect x="225" y="160" width="8" height="8" />
                <rect x="210" y="175" width="8" height="8" />
                <rect x="225" y="175" width="8" height="8" />
                
                <rect x="260" y="110" width="6" height="6" />
                <rect x="270" y="110" width="6" height="6" />
                <rect x="260" y="125" width="6" height="6" />
                <rect x="270" y="125" width="6" height="6" />
                <rect x="260" y="140" width="6" height="6" />
                <rect x="270" y="140" width="6" height="6" />
                <rect x="260" y="155" width="6" height="6" />
                <rect x="270" y="155" width="6" height="6" />
                <rect x="260" y="170" width="6" height="6" />
                <rect x="270" y="170" width="6" height="6" />
                
                <rect x="305" y="90" width="6" height="6" />
                <rect x="320" y="90" width="6" height="6" />
                <rect x="305" y="105" width="6" height="6" />
                <rect x="320" y="105" width="6" height="6" />
                <rect x="305" y="120" width="6" height="6" />
                <rect x="320" y="120" width="6" height="6" />
                <rect x="305" y="135" width="6" height="6" />
                <rect x="320" y="135" width="6" height="6" />
                <rect x="305" y="150" width="6" height="6" />
                <rect x="320" y="150" width="6" height="6" />
                <rect x="305" y="165" width="6" height="6" />
                <rect x="320" y="165" width="6" height="6" />
                
                <rect x="365" y="70" width="6" height="6" />
                <rect x="380" y="70" width="6" height="6" />
                <rect x="365" y="85" width="6" height="6" />
                <rect x="380" y="85" width="6" height="6" />
                <rect x="365" y="100" width="6" height="6" />
                <rect x="380" y="100" width="6" height="6" />
                <rect x="365" y="115" width="6" height="6" />
                <rect x="380" y="115" width="6" height="6" />
                <rect x="365" y="130" width="6" height="6" />
                <rect x="380" y="130" width="6" height="6" />
                <rect x="365" y="145" width="6" height="6" />
                <rect x="380" y="145" width="6" height="6" />
                <rect x="365" y="160" width="6" height="6" />
                <rect x="380" y="160" width="6" height="6" />
                
                <rect x="415" y="100" width="6" height="6" />
                <rect x="430" y="100" width="6" height="6" />
                <rect x="445" y="100" width="6" height="6" />
                <rect x="415" y="115" width="6" height="6" />
                <rect x="430" y="115" width="6" height="6" />
                <rect x="445" y="115" width="6" height="6" />
                <rect x="415" y="130" width="6" height="6" />
                <rect x="430" y="130" width="6" height="6" />
                <rect x="445" y="130" width="6" height="6" />
                <rect x="415" y="145" width="6" height="6" />
                <rect x="430" y="145" width="6" height="6" />
                <rect x="445" y="145" width="6" height="6" />
                <rect x="415" y="160" width="6" height="6" />
                <rect x="430" y="160" width="6" height="6" />
                <rect x="445" y="160" width="6" height="6" />
                <rect x="415" y="175" width="6" height="6" />
                <rect x="430" y="175" width="6" height="6" />
                <rect x="445" y="175" width="6" height="6" />
                
                <rect x="480" y="120" width="6" height="6" />
                <rect x="480" y="135" width="6" height="6" />
                <rect x="480" y="150" width="6" height="6" />
                <rect x="480" y="165" width="6" height="6" />
                <rect x="480" y="180" width="6" height="6" />
            </g>
            
            <!-- Roads -->
            <rect x="200" y="200" width="300" height="15" fill="#424242" />
            <rect x="320" y="200" width="15" height="100" fill="#424242" />
            
            <!-- Road markings -->
            <g fill="#FFFFFF" stroke="none">
                <rect x="200" y="207" width="20" height="2" />
                <rect x="240" y="207" width="20" height="2" />
                <rect x="280" y="207" width="20" height="2" />
                <rect x="320" y="207" width="20" height="2" />
                <rect x="360" y="207" width="20" height="2" />
                <rect x="400" y="207" width="20" height="2" />
                <rect x="440" y="207" width="20" height="2" />
                <rect x="480" y="207" width="20" height="2" />
                
                <rect x="326" y="220" width="2" height="20" />
                <rect x="326" y="260" width="2" height="20" />
            </g>
        </g>
        
        <!-- Rural area on right -->
        <g>
            <!-- Trees -->
            <path d="M550,200 L570,160 L590,200 Z" fill="#2E7D32" />
            <rect x="565" y="200" width="10" height="20" fill="#795548" />
            
            <path d="M600,200 L620,150 L640,200 Z" fill="#2E7D32" />
            <rect x="615" y="200" width="10" height="20" fill="#795548" />
            
            <path d="M520,200 L540,170 L560,200 Z" fill="#2E7D32" />
            <rect x="535" y="200" width="10" height="20" fill="#795548" />
            
            <!-- Small house -->
            <rect x="575" y="180" width="30" height="20" fill="#FFECB3" />
            <polygon points="575,180 605,180 590,165" fill="#D84315" />
        </g>
        
        <!-- Heat waves over city -->
        <g stroke="#FF5722" stroke-width="2" fill="none" stroke-dasharray="5,5">
            <path d="M220,120 C240,110 260,120 280,110 C300,100 320,110 340,100" />
            <path d="M260,90 C280,80 300,90 320,80 C340,70 360,80 380,70" />
            <path d="M300,60 C320,50 340,60 360,50 C380,40 400,50 420,40" />
        </g>
        
        <!-- Temperature scale -->
        <g>
            <defs>
                <linearGradient id="tempGradient" x1="0%" y1="0%" x2="100%" y2="0%">
                    <stop offset="0%" style="stop-color:blue;stop-opacity:1" />
                    <stop offset="50%" style="stop-color:yellow;stop-opacity:1" />
                    <stop offset="100%" style="stop-color:red;stop-opacity:1" />
                </linearGradient>
            </defs>
            
            <rect x="250" y="230" width="200" height="20" fill="url(#tempGradient)" />
            <text x="250" y="265" font-family="Arial" font-size="12" fill="#000">20°C</text>
            <text x="350" y="265" font-family="Arial" font-size="12" fill="#000">30°C</text>
            <text x="450" y="265" font-family="Arial" font-size="12" fill="#000">40°C</text>
            <text x="325" y="285" font-family="Arial" font-size="14" font-weight="bold" fill="#000">Urban Heat Island Effect</text>
        </g>
    </svg>
</div>
""", unsafe_allow_html=True)

# References section
st.markdown("""
## References and Further Reading

1. U.S. Environmental Protection Agency (EPA) - [Heat Island Effect](https://www.epa.gov/heatislands)
2. NASA Earth Observatory - [Urban Heat Islands](https://earthobservatory.nasa.gov/features/UrbanHeat)
3. C40 Cities - [Cool Cities Network](https://www.c40.org/networks/cool-cities)
4. Nature Conservancy - [Cooling a Warming City](https://www.nature.org/en-us/about-us/where-we-work/united-states/georgia/stories-in-georgia/urban-heat-atlanta/)
5. American Forests - [Tree Equity Score](https://www.americanforests.org/our-work/tree-equity-score/)

## Contact

For more information or to get involved in urban heat island mitigation efforts, contact your local environmental agency or urban planning department.
""")

# Footer
st.divider()
st.write("© 2023 Urban Heat Island Analyzer - A tool for mapping, analyzing, and addressing urban heat islands")
